language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: node-share-your-idea
  api_key:
    secure: QwZGC9GcfcgQjOVlM+3G/vabWGQHCzX950OJqHcZoHs/VTRdRf7WCRMdfZPCzqaoPqn/L1fthoVjPKzJtg2+byVmweigojy8m1KvjoE4Kj81krPHa79N7PGmrofcP4rAztBIuWLYeUgingvwbf22WgN0Mi7HuB8sVajRkn3fLvarwPyXoo2VvNYdlQOd8PpGb8beCytd3QpWy4cE2Vs1qn7O6RnyTkba2ee4Pgl+e89wdbQFHGcSjwFgPliDNad0VSUVTdsLdodKGLYh22Mth5GiRnwUfGhLz83DB+kS63Sc70VpygnhCvMI0ZCLBKVxx9RxZkdDCXzYZKB7kC4nXyEGM0yuwwXrT6XJ9REnqBfikgPC2RzaT3GKNASva4uE1lnsNx2Xyjq32SMSHEzVycH0BG0ub02dN7BNpf05m0sbAS2ncGB8PkorvRgrTUcfCF0jVPFXgvtKKRKNUmqORj+aSyCPOOvOKZi35bXwMUryBy/ZQw+u3sD4qSuMZjyixl7ZoNdlDkmt4FSr/eWKaTO5vDTsU5RxOeqE9dTRviND7xpfxIA8XJkJ5RyGmPJf5sNpGkIOap0mAjHdnuS/dtd097tPSa1ttKmvIKqoHoSLa9f9ONiJazmKHnXlHi6uOXt/ePid8ituib2vzu/N8/9QzbRVYQGsygMBhbrcbKA=
