version: '3'
services:
  app:
    build: .
    command: sh -c "npm run dev"
    volumes:
      - .:/myapp
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"

